from typing import Protocol


class IObservabilityService(Protocol):
    def observe_vacancy_collected(self, count: int = 1) -> None: ...

    def observe_not_vacancy_detected(self, count: int = 1) -> None: ...

    def observe_language_match(self, language: str, count: int = 1) -> None: ...
