"""empty message

Revision ID: 31ccfc502e51
Revises: 1ca1aaca3f85
Create Date: 2026-02-05 14:01:06.496403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ccfc502e51'
down_revision: Union[str, Sequence[str], None] = '1ca1aaca3f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_vacancies', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('raw_vacancies', sa.Column('message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_vacancies', 'message_id')
    op.drop_column('raw_vacancies', 'chat_id')
    # ### end Alembic commands ###
