"""del reason

Revision ID: 3a1007d2d014
Revises: d6a57e07cdea
Create Date: 2026-02-10 18:14:42.603100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1007d2d014'
down_revision: Union[str, Sequence[str], None] = 'd6a57e07cdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy_matches', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_matches', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
