"""empty message

Revision ID: 3f149b912ac8
Revises: 31ccfc502e51
Create Date: 2026-02-05 14:54:23.036712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f149b912ac8'
down_revision: Union[str, Sequence[str], None] = '31ccfc502e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_vacancies', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_vacancies', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
