"""ыфв

Revision ID: 5d9c11501e4a
Revises: 9e4cedcc38fd
Create Date: 2026-02-09 15:49:45.531666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9c11501e4a'
down_revision: Union[str, Sequence[str], None] = '9e4cedcc38fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('primary_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'primary_language')
    # ### end Alembic commands ###
