"""1

Revision ID: d4b21dbddcd2
Revises: 
Create Date: 2026-02-11 14:25:40.338513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4b21dbddcd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('text_resume', sa.Text(), nullable=True),
    sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience_months', sa.Integer(), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_experience_months', sa.Integer(), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mirror_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('mirror_message_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_matches')
    op.drop_table('vacancies')
    op.drop_table('users')
    # ### end Alembic commands ###
